package:
  name: axisUtilities
  version: '19.10.0'

source:
  git_url: https://github.com/maboualidev/yaamp.git
  git_rev: 19.10.0

build:
  noarch: python
  number: 0

requirements:
  build:
    - git
  run:
    - python
about:
  summary: Manages Axis and provides some utilities