{% set name = "axisutilities" %}
{% set version = "19.12.6.36596" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/coderepocenter/AxisUtilities.git
  git_rev: master
  
build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  number: 0

requirements:

  host:
    - python >3.5
    - pip
    - numpy
    - scipy
    - numba
    - dask
  run:
    - python >3.5
    - numpy
    - scipy
    - numba
    - dask

test:
  imports:
    - axisutilities
  source_files:
    - tests/
  commands:
    - python -m unittest
    
about:
  
  home: https://github.com/coderepocenter/AxisUtilities
  license: Apache 2.0
  license_file: LICENSE
  dev_url: https://github.com/coderepocenter/AxisUtilities
  doc_url: https://axisutilities.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - maboualidev
